import Navigation from "./components/navigation"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',  // 신경쓰지 않음
   
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html >
      
      <body>
      <Navigation />
      <hr />
      {children}</body>
    </html>
  )
}
